from mysql.connector imoprt connect, Error

try:
  with connect(
          host="localhost",
          user="username",
          password="password",
  ) as connection:
      create_db_query = "CREATE DATABASE my_database"
      with connection.cursor() as cursor:
          cursor.execute(create_db_query)
except Error as e:
  print(e)

